"""Initial migration

Revision ID: a906b8be1492
Revises: 
Create Date: 2024-10-09 12:19:53.905663

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a906b8be1492'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('professors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('image_id', sa.String(length=255), nullable=True),
    sa.Column('username', sa.String(length=255), nullable=True),
    sa.Column('avesis_id', sa.Integer(), nullable=True),
    sa.Column('faculty_id', sa.Integer(), nullable=True),
    sa.Column('departments', sa.String(length=1023), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('avesis_id')
    )
    op.create_index(op.f('ix_professors_full_name'), 'professors', ['full_name'], unique=False)
    op.create_index(op.f('ix_professors_id'), 'professors', ['id'], unique=False)
    op.create_index(op.f('ix_professors_username'), 'professors', ['username'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=True),
    sa.Column('gmail', sa.String(length=255), nullable=True),
    sa.Column('admin', sa.Boolean(), nullable=True),
    sa.Column('verified', sa.Boolean(), nullable=True),
    sa.Column('student_email', sa.String(length=255), nullable=True),
    sa.Column('google_id', sa.String(length=255), nullable=True),
    sa.Column('picture', sa.String(length=1024), nullable=True),
    sa.Column('locale', sa.String(length=50), nullable=True),
    sa.Column('verification_code', sa.String(length=64), nullable=True),
    sa.Column('verification_code_expires', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_email')
    )
    op.create_index(op.f('ix_users_full_name'), 'users', ['full_name'], unique=False)
    op.create_index(op.f('ix_users_gmail'), 'users', ['gmail'], unique=True)
    op.create_index(op.f('ix_users_google_id'), 'users', ['google_id'], unique=True)
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('professor_id', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=1000), nullable=True),
    sa.Column('english_proficiency', sa.Integer(), nullable=True),
    sa.Column('friendliness', sa.Integer(), nullable=True),
    sa.Column('knowledge', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.CheckConstraint('english_proficiency >= 5 AND english_proficiency <= 50 AND english_proficiency % 5 = 0'),
    sa.CheckConstraint('friendliness >= 5 AND friendliness <= 50 AND friendliness % 5 = 0'),
    sa.CheckConstraint('knowledge >= 5 AND knowledge <= 50 AND knowledge % 5 = 0'),
    sa.ForeignKeyConstraint(['professor_id'], ['professors.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ratings_id'), 'ratings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ratings_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_index(op.f('ix_users_google_id'), table_name='users')
    op.drop_index(op.f('ix_users_gmail'), table_name='users')
    op.drop_index(op.f('ix_users_full_name'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_professors_username'), table_name='professors')
    op.drop_index(op.f('ix_professors_id'), table_name='professors')
    op.drop_index(op.f('ix_professors_full_name'), table_name='professors')
    op.drop_table('professors')
    # ### end Alembic commands ###
