"""actually verification for real

Revision ID: d8fb75c04061
Revises: 8326cb099bdc
Create Date: 2024-10-29 21:00:57.422408

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd8fb75c04061'
down_revision: Union[str, None] = '8326cb099bdc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('verification_attempts', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('last_verification_attempt', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'last_verification_attempt')
    op.drop_column('users', 'verification_attempts')
    # ### end Alembic commands ###
